apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-keycloak-public
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: craigmiller160@gmail.com
    privateKeySecretRef:
      name: letsencrypt-keycloak-public
    solvers:
      - http01:
          ingress:
            class: public
---
{{/*apiVersion: cert-manager.io/v1*/}}
{{/*kind: ClusterIssuer*/}}
{{/*metadata:*/}}
{{/*  name: letsencrypt-keycloak-private*/}}
{{/*spec:*/}}
{{/*  acme:*/}}
{{/*    server: https://acme-v02.api.letsencrypt.org/directory*/}}
{{/*    email: craigmiller160@gmail.com*/}}
{{/*    privateKeySecretRef:*/}}
{{/*      name: letsencrypt-keycloak-private*/}}
{{/*    solvers:*/}}
{{/*      - http01:*/}}
{{/*          ingress:*/}}
{{/*            class: public*/}}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Chart.Name }}-internal
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}-internal
spec:
  isCA: true
  commonName: {{ .Chart.Name }}-internal
  secretName: {{ .Chart.Name }}-internal
  dnsNames:
    - auth-craigmiller160.ddns.net
    - craigmiller160.ddns.net
    - localhost
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ .Chart.Name }}-internal
    kind: ClusterIssuer
    group: cert-manager.io