apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
  # TODO these credentials need to come from 1Password
  KC_DB_PASSWORD: password
  KC_DB_USERNAME: user
