apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "quay.io/keycloak/keycloak:{{ .Values.imageTag }}"
          imagePullPolicy: IfNotPresent
          args:
            - start
            - --hostname-strict=false
            - --proxy=edge
            - --https-certificate-file=/certs/tls.crt
            - --https-certificate-key-file=/certs/tls.key
          ports:
            - containerPort: {{ .Values.port }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ .Chart.Name }}-admin-user
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Chart.Name }}-admin-user
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ .Chart.Name }}-postgres
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Chart.Name }}-postgres
          volumeMounts:
            - mountPath: /certs
              name: certs-volume
          readinessProbe: {{ .Values.probe | toYaml | trim | nindent 12 }}
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 5
          livenessProbe: {{ .Values.probe | toYaml | trim | nindent 12 }}
            initialDelaySeconds: 30
            periodSeconds: 300
            failureThreshold: 3
      volumes:
        - name: certs-volume
          secret:
            secretName: {{ .Chart.Name }}-internal
