apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-public-ingress
  annotations:
    kubernetes.io/ingress.class: public
    cert-manager.io/cluster-issuer: letsencrypt-keycloak-public
    nginx.ingress.kubernetes.io/proxy-body-size: 1000m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 32k
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
    - host: auth-craigmiller160.ddns.net
      http:
        paths:
          - path: /js/.*
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.port }}
          - path: /realms/.*
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.port }}
          - path: /resources/.*
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.port }}
          - path: /robots.txt
            pathType: Exact
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.port }}
  tls:
    - secretName: letsencrypt-keycloak-public
      hosts:
        - auth-craigmiller160.ddns.net
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-private-ingress
  annotations:
    kubernetes.io/ingress.class: public
    cert-manager.io/cluster-issuer: letsencrypt-keycloak-private
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: 1000m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 32k
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/whitelist-source-range: 47.196.14.245/32, 192.168.0.0/16
spec:
  rules:
    - host: auth-craigmiller160.ddns.net
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.port }}
  tls:
    - secretName: letsencrypt-keycloak-private
      hosts:
        - auth-craigmiller160.ddns.net